
 homeText = "You just made a Hugo blog from scratch."
 copyrighthtml = "Copyright &#xA9; 2017 John Doe. All Rights Reserved."
 sidebarrecentlimit = 5
 twitteruser = "spf13"

[alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"